const nome = prompt('Digite seu nome completo: ');
let tamanho = nome.length;
let secondLeter = nome[1]
let firstLeterA = nome.indexOf('a')
let lastLeterA = nome.lastIndexOf('a',)
let lastLeters = nome.slice(-3)
let splitName = nome.split(' ')
let UPnome = nome.toUpperCase()
let downNome = nome.toLowerCase()
document.body.innerHTML += `Seu nome é: ${nome} <br />`;
document.body.innerHTML += `Seu tem ${tamanho} letras <br />`;
document.body.innerHTML += `A segunda letra do seu nome é: ${secondLeter}<br />`;
document.body.innerHTML += `Qual o primeiro indice da letra a no seu nome? ${firstLeterA}<br />`;
document.body.innerHTML += `Qual o ultimo indice da letra a no seu nome? ${lastLeterA}<br />`;
document.body.innerHTML += `As últimas 3 letras do seu nome são: ${lastLeters}<br />`;
document.body.innerHTML += `As palavras do seu nome são: ${splitName} <br /> `;
document.body.innerHTML += `Seu nome com letras maiúsculas: ${UPnome} <br /> `;
document.body.innerHTML += `Seu nome com letras minúsculas: ${downNome} <br /> `;
